### ISSUE TITLE
Feature Request: add a command to open an HTML Preview on the side

### ISSUE THREAD

**Issue by stef-levesque** [stef-levesque/vscode-link#1]
@thelmgn could you explain more what you are expecting from this ?

Related: microsoft/vscode#28263

**Comment by foxt** [comment]
I have no idea what you mean.

Did you mention the wrong user or are you referring to my review on a extension?

**Comment by stef-levesque** [comment]
Yes, about your comment in the review, what exactly would you like to see in this extension.

**Comment by foxt** [comment]
I think what I meant was add it to the command picker. Not sure about it though.
